services:
  - type: web
    name: tinylink
    env: node
    plan: free
    region: oregon
    branch: main
    buildCommand: npm ci
    startCommand: npm start
    releaseCommand: npm run migrate:node
    envVars:
      - key: DATABASE_URL
        sync: false
